# main34.py is a part of the PYTHIA event generator.
# Copyright (C) 2023 Torbjorn Sjostrand.
# PYTHIA is licenced under the GNU GPL v2 or later, see COPYING for details.
# Please respect the MCnet Guidelines, see GUIDELINES for details.

# Authors:
#            Philip Ilten

# Keywords:
#            Matching
#            Madgraph
#            aMC@NLO
#            Python

# An example where the hard process (p p -> mu+ mu-) is generated by Pythia.


# To set the path to the Pythia 8 Python interface do either (in a
# shell prompt):
#      export PYTHONPATH=$(PREFIX_LIB):$PYTHONPATH
# or the following which sets the path from within Python.
import sys
import numpy as np
cfg = open('Makefile.inc')
lib = '../lib'
for line in cfg:
    if line.startswith('PREFIX_LIB='): lib = line[11:-1]; break
sys.path.insert(0, lib)
import pythia8

#==========================================================================

# A simple method to run Pythia, analyze the events, and fill a histogram.

def run(pythia, nEvent): 
  pt = []
  m = []
  pythia.readString("Random:setSeed = on")
  pythia.readString("Random:seed = 1")
  pythia.init()
  for iEvent in range(0, nEvent):
      if not pythia.next(): continue
      iMu1 = 0; iMu2 = 0
      for prt in pythia.event:
          if not iMu1 and prt.id() == 13:  iMu1 = prt.index()
          if not iMu2 and prt.id() == -13: iMu2 = prt.index()
          if iMu1 and iMu2:
              iMu1 = pythia.event[iMu1].iBotCopyId()
              iMu2 = pythia.event[iMu2].iBotCopyId()
              pt.append((pythia.event[iMu1].p() + pythia.event[iMu2].p()).pT())
              m.append((pythia.event[iMu1].p() + pythia.event[iMu2].p()).mCalc())
              break
  pythia.stat()
  return np.array(pt), np.array(m)


# Produce leading-order events with Pythia.
pythia = pythia8.Pythia()
pythia.readString("Beams:eCM = 13000.")
pythia.readString("WeakSingleBoson:ffbar2gmZ = on")
pythia.readString("23:onMode = off")
pythia.readString("23:onIfMatch = -13 13")
pythia.readString("PhaseSpace:mHatMin = 80.")
pyPtZArray, pyMZArray = run(pythia, 1000)

import mplhep as hep
import matplotlib.pyplot as plt
plt.style.use(hep.style.CMS)

plt.figure()
plt.subplot(211)
plt.hist(pyPtZArray, bins=np.linspace(0, 120, 100), label='Pythia')
plt.xlabel("$p_{T}(Z)$ [GeV]")
plt.ylabel("Events")
plt.legend()
plt.subplot(212)
plt.hist(pyMZArray, bins=np.linspace(60, 120, 100), label='Pythia')
plt.xlabel("$m(Z)$ [GeV]")
plt.ylabel("Events")
plt.legend()
plt.tight_layout()
plt.savefig("pythia.pdf")